-- Taller database
CREATE DATABASE IF NOT EXISTS Universidad;
USE Universidad;

CREATE DATABASE IF NOT EXISTS Universidad;
USE Universidad;

CREATE TABLE IF NOT EXISTS Sexo (
    ID_SEXO VARCHAR(4) PRIMARY KEY,
    SEXO TEXT
);

CREATE TABLE IF NOT EXISTS Carrera (
    ID_CARRERA VARCHAR(4) PRIMARY KEY,
    CARRERA TEXT
);

CREATE TABLE IF NOT EXISTS Materias (
    ID_MATERIA VARCHAR(4) PRIMARY KEY,
    MATERIA TEXT
);

CREATE TABLE IF NOT EXISTS Datos_maestro (
    ID_MAESTRO VARCHAR(4) PRIMARY KEY,
    NOMBRE TEXT,
    DIRECCION VARCHAR(10),
    TELEFONO VARCHAR(10),
    ID_SEXO VARCHAR(4),
    ID_CARRERA VARCHAR(4),
    FOREIGN KEY (ID_SEXO) REFERENCES Sexo(ID_SEXO),
    FOREIGN KEY (ID_CARRERA) REFERENCES Carrera(ID_CARRERA)
);

CREATE TABLE IF NOT EXISTS Asignacion (
    ID_MAESTRO VARCHAR(4),
    ID_MATERIA VARCHAR(4),
    PRIMARY KEY (ID_MAESTRO, ID_MATERIA),
    FOREIGN KEY (ID_MAESTRO) REFERENCES Datos_maestro(ID_MAESTRO),
    FOREIGN KEY (ID_MATERIA) REFERENCES Materias(ID_MATERIA)
);

INSERT IGNORE INTO Sexo (ID_SEXO, SEXO) VALUES 
('M', 'Masculino'),
('F', 'Femenino');


INSERT IGNORE INTO Carrera (ID_CARRERA, CARRERA) VALUES 
('C1', 'Ingeniería'),
('C2', 'Matemáticas');

INSERT IGNORE INTO Materias (ID_MATERIA, MATERIA) VALUES 
('M001', 'Álgebra'),
('M002', 'Programación');

INSERT IGNORE  INTO Datos_maestro (ID_MAESTRO, NOMBRE, DIRECCION, TELEFONO, ID_SEXO, ID_CARRERA) VALUES 
('T001', 'Carlos Pérez', 'Cra10#20', '1234567890', 'M', 'C1'),
('T002', 'Laura Gómez', 'Cll5#30', '0987654321', 'F', 'C2');


INSERT IGNORE INTO Asignacion (ID_MAESTRO, ID_MATERIA) VALUES 
('T001', 'M001'),
('T002', 'M002');
